checks:
    javascript: true

build:
    tests:
        override:
            -
                command: 'npm run test'
                coverage:
                    file: 'coverage/clover.xml'
                    format: 'clover'
